### ISSUE TITLE
XSS FP with 'on' in URL query parameters

### ISSUE THREAD

**Issue by lifeforms** [client9/libinjection#115]
In the OWASP CRS 3.0.0, I am seeing lots of false positives from URLs containing `on` phrase (see https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/663 for our issue). The FP can also happen in other variables, but apparently that is a lot more rare.

Some simplified versions of different urls, which are detected as XSS:

- `curl --referer 'http://www.bing.com/search?q=design+ontwerp&go=Search' http://localhost/`
- `curl --referer 'http://example.com/vacatures?q=Industrieel+Ontwerper&matchtype=b' http://localhost/`
- `curl --referer 'http://example.com/search&name=music+on&color=&logo=' http://localhost/`

A common pattern in the FPs above is the use of `on` phrase in the query parameters of the referrer URL. E.g. `ontwerp`, `ontwerpen`, `music on`. If you modify the `on` to `ox`, the FP disappears.

So, libinjection sees ` onfoo&bar=` as XSS. This might not be an unreasonable guess, in case there are browsers which "autocorrect" the `&foo` and ignore it. At the other hand, maybe it's overzealous.

I've checked with a new libinjection from master and it is still firing on these contents:

Payload | Result
--------|-------
`http://www.bing.com/search?q=design ontwerp&go=Search` | xss
`http://example.com/vacatures?q=Industrieel Ontwerper&matchtype=b` | xss
`http://example.com/search&name=music on&color=&logo=` | xss
`onfoo=1` | xss
`onfoo&bar=1` | xss
`fonfoo&bar=1` | not xss
`onfoo&bar&bor=1` | xss

This might be a hard case, could it be handled specifically?

**Comment by fengjian** [comment]
look this:

https://github.com/client9/libinjection/blob/master/src/libinjection_xss.c

335 line:
static attribute_t is_black_attr(const char* s, size_t len)
{
    stringtype_t* black;

    if (len < 2) {
        return TYPE_NONE;
    }

    /* JavaScript on.* */
    if ((s[0] == 'o' || s[0] == 'O') && (s[1] == 'n' || s[1] == 'N')) {
        /* printf("Got JavaScript on- attribute name\n"); */
        return TYPE_BLACK;
}

**Comment by client9** [comment]
I believe this is fixed now.  PR welcome if not.
