### ISSUE TITLE
Missing most attacks when using --tamper=apostrophemask with SQLMAP

### ISSUE THREAD

**Issue by bararchy** [client9/libinjection#89]
This is the tamper file: https://github.com/sqlmapproject/sqlmap/blob/master/tamper/apostrophemask.py

If you need I can output all strings into a file and copy here

**Comment by client9** [comment]
got 'em.  thanks for report.

To work around this you can do a UTF8 normalization before calling libinjection.

**Comment by client9** [comment]
thats said, Im not sure what database actually allows this, or if this is an application bypass that does a UTF8 normalization first.

**Comment by bararchy** [comment]
@client9 Thanks for the tip, I'll do that.

Closed.
