### ISSUE TITLE
False positive

### ISSUE THREAD

**Issue by huangchen007** [client9/libinjection#91]
Nick, any idea why strings (below)  is flagged as SQLi?

"Select count(*) from Monitor" detected with fingerprint of 'Ef(o)'
"Select * from Monitor where ID = 182517" detected with fingerprint of 'Eoknk'

**Comment by client9** [comment]
if the query is like this, then those will be "SQLi".
`select * from table where id=($INPUT)`

Feel free to remove the  'Ef(o)',  'Eoknk' fingerprints .

JIRA for instance allows "sql-like" inputs.  I would white list these fields.

good luck

**Comment by huangchen007** [comment]
I 'm sorry to bother you again.
What can I do with the source code if I want to remove the 'Ef(o)', 'Eoknk' fingerprints.

**Comment by huangchen007** [comment]
It's done with modifying fingerprints.txt.
Is that right？

**Comment by client9** [comment]
YES,

But better you can check the fingerprint  that comes out of IsSQLI and
compare to your whitelist.

On Wed, Jul 22, 2015 at 1:07 AM, C.Wong <notifications@github.com> wrote:

> It's done with modifying fingerprints.txt.
> Is that right？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/client9/libinjection/issues/91#issuecomment-123609351>
> .
>



-- 
Nick Galbreath  | Founder / CTO          | @ngalbreath     |
Signal Sciences | www.signalsciences.com | @signalsciences |

**Comment by huangchen007** [comment]
One more question. I couldn't find any code that manipulate fingerprint.txt. How do I control whitelist or blacklist?

**Comment by huangchen007** [comment]
oh, I understand. I read Makefile carefully and then know your design completely
